### ISSUE TITLE
OS/2 fsSelection WWS bit should be set

### ISSUE THREAD

**Issue by moontypespace** [notofonts/notofonts.github.io#27]
### Font 
Fonts stored here: https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/googlefonts/ttf

### Where the font came from, and when
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/googlefonts/ttf

### Font Version
Version 2.012; ttfautohint (v1.8.4.7-5d5b)

### Issue
According to the OpenType Spec the WWS bit should be set:
„The font has 'name' table strings consistent with a weight/width/slope family without requiring use of name IDs 21 and 22. “
https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection

**Comment by simoncozens** [comment]
Isn't this https://github.com/notofonts/latin-greek-cyrillic/issues/227? (Please open Noto issues in the repository for the relevant script - thanks!)

**Comment by moontypespace** [comment]
I thought, this is the new repository. Am I wrong?

**Comment by simoncozens** [comment]
"Noto Sans" and "Noto Serif" sources live in notofonts/latin-greek-cyrillic. You can find the right repo to report a font bug [here](https://notofonts.github.io/reporter.html).

**Comment by moontypespace** [comment]
Thanks a lot, @simoncozens . I will use it the next time. But this issue is not tied to a specific script, isn't it? It's more a general thing I noticed. If you agree with me, you may want to check all other fonts as well, not just the 'latin-greek-cyrillic'.

**Comment by simoncozens** [comment]
It is a general issue, I suppose, and one to do with the font building process. I'm vaguely surprised we don't have a fontbakery QA check for this bit. I think this is because historically Google Fonts focused on static files without the width axis, so never needed to get into the whole WWS thing. Now we create instances of variable fonts with a width axis, it may be worth revisiting. But it will affect lots of areas: the build chain, the QA process, and so on. I'll check with colleagues and find a suitable place to discuss.
