### ISSUE TITLE
two directories for looped Thai

### ISSUE THREAD

**Issue by berrymot** [notofonts/notofonts.github.io#35]
fonts/ in this repo contains both NotoLoopedThai/ and NotoSansThaiLooped/.... I *think* the files in them are identical other than the name change

**Comment by simoncozens** [comment]
Sans Thai Looped is the correct one. ("Noto *Style* *Script* [*Variant*]") I'll remove the other.

**Comment by berrymot** [comment]
thanku :3

**Comment by iwsfutcmd** [comment]
Noto Looped Thai is still showing up in `index.html`. Stripping `Noto Looped Thai` out of `state.json` and `noto.json` and rerunning `build-site.py` fixes this, but rerunning `gather.py` puts `Noto Looped Thai` back into those json files, so I'm guessing the issue is https://github.com/notofonts/thai still has a `Noto Looped Thai` tag.
